theme = "gruvbox"

[editor]
auto-completion = true
line-number = 'relative'
color-modes = true
bufferline = "multiple"

[editor.lsp]
display-messages = true
display-signature-help-docs = true

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"


[keys.insert]
"A-x" = "normal_mode" # Maps Alt-X to enter normal mode
j = { j = "normal_mode" } # Maps `jk` to exit insert mode

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

# or control each character
[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = " "
nbsp = "⍽"
tab = ">"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)# At most one section each of 'keys.normal', 'keys.insert' and 'keys.select'

[editor.indent-guides]
render = true

[keys.normal]
C-o = ":open ~/.config/helix/config.toml" # Maps the Control-o to opening of the helix config file
"C-S-esc" = "extend_line" # Maps Control-Shift-Escape to extend_line
g = { a = "code_action" } # Maps `ga` to show possible code actions
"ret" = ["open_below", "normal_mode"] # Maps the enter key to open_below then re-enter normal mode
tab = {n = ":bn", p = ":bp"}
space = {w = ":w", c = { o = ":config-open", r = ":config-reload"}}
